[package]
name = "crossterm_input"
version = "0.1.0"
authors = ["T. Post"]
description = "A cross-platform library for reading userinput."
repository = "https://github.com/TimonPost/crossterm"
documentation = "https://docs.rs/crossterm_input/"
license = "MIT"
keywords = ["input", "keys", "crossterm", "crossplatform", "terminal"]
exclude = ["target", "Cargo.lock"]
readme = "README.md"
edition = "2018"

[target.'cfg(windows)'.dependencies]
winapi = { version =  "0.3.5", features = ["winnt"] }
crossterm_winapi = { path = "../crossterm_winapi" }

[dependencies]
crossterm_utils = { path = "../crossterm_utils" }

[[example]]
name = "input"
path = "examples/input.rs"

[[example]]
name = "async_input"
path = "examples/async_input.rs"