[package]
name = "crossterm_utils"
version = "0.1.0"
authors = ["Timon Post <timonpost@hotmail.nl>"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
crossterm_winapi = "0.1.1"
winapi = { version =  "0.3.7", features = ["wincon"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.51"